# Generated by Django 6.0.1 on 2026-02-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField(unique=True)),
                ('student_class', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('parent_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
